import "@/styles/globals.css"
import {Inter as FontSans} from "next/font/google"

import {cn} from "@/lib/utils"
import {Metadata} from "next";
import DemoNavBar from "@/components/DemoNavBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "dark min-h-screen bg-background font-sans antialiased bg-black",
          fontSans.variable
        )}
      >
        <div>
          <DemoNavBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
